### ISSUE TITLE
installation instructions?

### ISSUE THREAD

**Issue by tastez** [hustille/ComfyUI_Fooocus_KSampler#1]
hi, does this differ from regular custom nodes installation? Im getting an import error Would be great to have an example node setup too as an image

**Comment by hustille** [comment]
I've seen that error once on one machine, but am struggling to reproduce it - working on it ...

**Comment by hustille** [comment]
Ok, the last revision of ComfyUI renamed load_additional_models to get_additional_models. The portable windows version has not been updated yet. Unsure how to resolve this ...

**Comment by hustille** [comment]
I patched it. Please pull the new version and check whether this works.

**Comment by tastez** [comment]
great it loads! thank you for patching.
I have 0 idea how to wire it up however so an example would be great. My own attempt caused errors, but i didnt use a refiner and just plugged in the same sdxl model

**Comment by hustille** [comment]
There already is an example. Look for `test ksampler refiner.json` in the module dir.

**Comment by tastez** [comment]
> There already is an example. Look for `test ksampler refiner.json` in the module dir.

cool - was expecting a screenshot and forgot jsons work too.
I dragged it in, it loaded everything up - i changed some models but got an error
```
 Prompt outputs failed validation
CLIPTextEncodeSDXL:
- Return type mismatch between linked nodes: text_g, ASCII != STRING
- Return type mismatch between linked nodes: text_l, ASCII != STRING
CLIPTextEncodeSDXL:
- Return type mismatch between linked nodes: text_g, ASCII != STRING
- Return type mismatch between linked nodes: text_l, ASCII != STRING
CLIPTextEncodeSDXLRefiner:
- Return type mismatch between linked nodes: text, ASCII != STRING
```

**Comment by jepjoo** [comment]
I had the import error aswell on Windows. Fixed by update, however, I get this error when using "test ksampler refiner.json"

100%|█████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.38it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus_KSampler\sampler\nodes.py", line 49, in sample
    return (core.ksampler_with_refiner(model, positive, negative, refiner_model, refiner_positive, refiner_negative, latent_image, noise_seed, steps, refiner_switch_step, cfg, sampler_name, scheduler, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise), )
  File "G:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus_KSampler\sampler\Fooocus\core.py", line 252, in ksampler_with_refiner
    comfy.sample.cleanup_additional_modelsst_cond(models)
AttributeError: module 'comfy.sample' has no attribute 'cleanup_additional_modelsst_cond'

Prompt executed in 11.56 seconds

**Comment by hustille** [comment]
Both problems should be fixed now. Please try again.

**Comment by jepjoo** [comment]
> Both problems should be fixed now. Please try again.

Works now with test ksampler refiner.json

Thanks!

**Comment by tastez** [comment]
still blowing up here for some reason
```

Failed to validate prompt for output 9:
* CLIPTextEncodeSDXL 17:
  - Return type mismatch between linked nodes: text_g, ASCII != STRING
  - Return type mismatch between linked nodes: text_l, ASCII != STRING
* CLIPTextEncodeSDXL 22:
  - Return type mismatch between linked nodes: text_g, ASCII != STRING
  - Return type mismatch between linked nodes: text_l, ASCII != STRING
* CLIPTextEncodeSDXLRefiner 23:
  - Return type mismatch between linked nodes: text, ASCII != STRING
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

```

**Comment by tastez** [comment]
ended up rewiring some things and the node is working really well!
